### ISSUE TITLE
中文识别时  网络输入图像大小

### ISSUE THREAD

**Issue by zgq91** [kouxichao/crnn#4]
您好:
    请问一下中文字符识别的时候 网络输入图像大小是多少

**Comment by kouxichao** [comment]
这个我忘记了，应该是这个，，
![image](https://user-images.githubusercontent.com/18493402/67550113-49ce5900-f738-11e9-8c77-9507bd9ac3de.png)
你可以看ncnn的params确认一下

**Comment by zgq91** [comment]
非常感谢回复，crnn/examples/crnn_chinese.cpp中 print_topk函数中存在一个bug，classes数组不管设置成多大都会存在count 越界问题；请问这个是什么原因导致的

**Comment by kouxichao** [comment]
@zgq91 这个没办法说清楚， 我测试过应该是没有问题，可以的话，你上传一下错误信息，

**Comment by zgq91** [comment]
应该是windows下的原因，ubuntu16.04下没有问题
